### ISSUE TITLE
segfault on query condition or order_by

### ISSUE THREAD

**Issue by dacort** [actsasflinn/ruby-tokyotyrant#1]
Moving a script from my OS X development box to an ec2 image, the query condition and order_by methods now cause a segfault. The output below shows order_by.

irb(main):003:0> t = TokyoTyrant::Table.new('127.0.0.1', 1979)
=> #<TokyoTyrant::Table:0x2b2cdd59cd80 @rdb=#<Object:0x2b2cdd59cd58>, @host="127.0.0.1", @port=1979>
irb(main):004:0> 
irb(main):005:0\* q = t.query  
=> #<TokyoTyrant::Query:0x2b2cdd598578 @rdb=#<Object:0x2b2cdd59cd58>, @rdbquery=#Object:0x2b2cdd598550>
irb(main):006:0> q.count
=> 3778
irb(main):007:0> q.limit(10)  
=> #<TokyoTyrant::Query:0x2b2cdd598578 @rdb=#<Object:0x2b2cdd59cd58>, @rdbquery=#Object:0x2b2cdd598550>
irb(main):008:0> q.count
=> 10
irb(main):009:0> q.search
=> # returns successfully
irb(main):010:0> q.order_by('count', :numdesc)
(irb):10: [BUG] Segmentation fault
ruby 1.8.6 (2007-09-24) [x86_64-linux]

**Comment by actsasflinn** [comment]
Is this from the gem or from a cloned repo?

**Comment by dacort** [comment]
From the gem - will try updating to 0.1.7 and see if that helps.

**Comment by dacort** [comment]
Didn't seem to help, unfortunately.

**Comment by actsasflinn** [comment]
Can you tell me what version of cabinet and tyrant you are testing against?

The formatting on the ticket is broken but I think I got it.  I ran the following without error.  Did I get your post right?

<pre>
irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'tokyo_tyrant'
=> true
irb(main):003:0> t = TokyoTyrant::Table.new('127.0.0.1', 1979)
=> #<TokyoTyrant::Table:0x1322660 @server="127.0.0.1:1979", @timeout=0.0, @port=1979, @rdb=#<Object:0x13225e8>, @host="127.0.0.1", @retry=false>
irb(main):004:0> 
irb(main):005:0* q = t.query
=> #<TokyoTyrant::Query:0x131dd90 @rdbquery=#<Object:0x131dd68>, @rdb=#<Object:0x13225e8>>
irb(main):006:0> q.count
=> 536
irb(main):007:0> q.limit(10)
=> #<TokyoTyrant::Query:0x131dd90 @rdbquery=#<Object:0x131dd68>, @rdb=#<Object:0x13225e8>>
irb(main):008:0> q.count
=> 10
irb(main):009:0> q.search
=> ["3348", "4320", "4888", "4700", "4698", "3397", "3349", "4321", "4889", "4699"]
irb(main):010:0> q.order_by('code', :numdesc)
=> #<TokyoTyrant::Query:0x131dd90 @rdbquery=#<Object:0x131dd68>, @rdb=#<Object:0x13225e8>>
irb(main):011:0> q.search
=> ["47251", "46341", "42461", "34173", "33673", "33653", "33543", "4948", "4942", "4938"]
</pre>

**Comment by dacort** [comment]
Sorry about that formatting - Cabinet is 1.4.23 and Tyrant is 1.1.27. Removing the toupper in the cQuery_addcond method appears to have fixed it there as well.

**Comment by actsasflinn** [comment]
This should be resolved in 0.1.8, thanks
