### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by brw314** [actsasflinn/ruby-tokyotyrant#2]
I'm new to ruby, but I get this when I follow your directions. Do I need to install the gem locally first?

zephyr:/sbin root# sudo gem install ruby-tokyotyrant --source=http://gemcutter.org
ERROR:  While executing gem ... (Gem::GemNotFoundException)
    Could not find ruby-tokyotyrant (> 0) in any repository
zephyr:/sbin root#

**Comment by actsasflinn** [comment]
What version of ruby and rubygems do you have installed?
