### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by brw314** [actsasflinn/ruby-tokyotyrant#3]
also I tried building locally:

zephyr:/Users/rberger/Desktop/ruby-tokyotyrant root# rake  
(in /Users/rberger/Desktop/ruby-tokyotyrant)
rake aborted!
undefined method `add_runtime_dependency' for #Gem::Specification:0x562e58
/Users/rberger/Desktop/ruby-tokyotyrant/rakefile:43
(See full trace by running task with --trace)

**Comment by actsasflinn** [comment]
What version of ruby and rubygems are you using?

**Comment by blaskovicz** [comment]
I figured this out on my end; I needed to move said line after `spec.add_development_dependency "bundler"`

**Comment by actsasflinn** [comment]
Good to have closure. Feels like yesterday this was new.
